# Generated by Django 5.2 on 2025-05-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
