# Generated by Django 5.2 on 2025-05-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_rentadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='future_rent_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Scheduled rent to take effect on rent_change_date', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='rent_change_date',
            field=models.DateField(blank=True, help_text='Date when future_rent_amount becomes active', null=True),
        ),
    ]
