# Generated by Django 5.2 on 2025-05-10 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_unit_future_rent_amount_unit_rent_change_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='future_rent_amount',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='rent_change_date',
        ),
    ]
